# Function to read the data from folder

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn import svm, metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.metrics import accuracy_score,confusion_matrix,roc_curve, auc
from matplotlib import pyplot as plt
from collections import Counter
from scipy.stats import norm, zscore
import seaborn as sns; sns.set(font_scale=1.2)
from sklearn.externals import joblib
%matplotlib inline

In [6]:
# # Std normalization process
# def readnormalized(path, filename):
#     datafeatures=pd.read_csv(path+filename,header=None)
#     dfr=datafeatures[datafeatures.columns[0]]
#     df=datafeatures[datafeatures.columns[1:]]
# #     dzs=df.apply(zscore)
#     min_max_scaler = preprocessing.MinMaxScaler()
#     scaled_array = min_max_scaler.fit_transform(df)
#     dfn=scaled_array
#     df_normalized = pd.DataFrame(dfn)
#     da=pd.concat([dfr, df_normalized],axis=1)
#     return da;

In [7]:
# path='C:/Users/Sultan/OneDrive - The University of Memphis/RESEARCH2017S/Msos/ACA-Code-master/Features/';
# filename='Effects5Features.csv'
# eff=readnormalized(path, filename)
# hum=readnormalized(path,'Human5Features.csv')
# mus=readnormalized(path,'Music5Features.csv')
# nat=readnormalized(path,'Nature5Features.csv')
# urb=readnormalized(path,'Urban5Features.csv')

In [40]:
# All=pd.concat([eff, hum,mus,nat,urb], axis=0)
# # eff.head()
# All

# Write the Xls file

In [41]:
# writer = pd.ExcelWriter(path+'allstdscore.xlsx')
# All.to_excel(writer,'Sheet1')
# writer.save()

In [42]:
# TrainLabel=pd.read_csv(path+'Logsheet_Development.csv')
# b=All[0].tail()
#print TrainLabel 
#TrainLabel['File']

#  Reading csv data

In [43]:
path='C:/Users/Sultan/OneDrive - The University of Memphis/RESEARCH2017S/Msos/ACA-Code-master/Features/';
TrainLabel=pd.read_csv(path+'Logsheet_Development.csv')
#NewAll=pd.read_csv('all.csv')
# First need to add a 'FileName' in the 2nd column and delet the first column
NewAll=pd.read_csv(path+'allstdscore.csv')
NewAll.columns = NewAll.columns.astype(str)

In [44]:
NewAll.head()

FileName         0         1         2         3         4         5  \
0  03J.wav  0.534103  0.119948  0.892717  0.713974  0.448908  0.595151   
1  07L.wav  0.681662  0.317390  0.131678  0.720654  0.503279  0.571534   
2  0M8.wav  0.764563  0.274184  0.293659  0.757733  0.445074  0.632836   
3  0UB.wav  0.628819  0.384421  0.513525  0.768080  0.533338  0.616659   
4  0W9.wav  0.402282  0.020001  0.407166  0.756747  0.604956  0.595541   

          6         7         8    ...           18        19        20  \
0  0.505618  0.676772  0.378105    ...     0.049758  0.026326  0.025489   
1  0.492099  0.654283  0.400897    ...     0.062783  0.030241  0.029785   
2  0.501671  0.767431  0.430402    ...     0.146451  0.028565  0.026865   
3  0.513200  0.730376  0.445957    ...     0.100594  0.062772  0.050559   
4  0.486649  0.547777  0.624267    ...     0.105882  0.090564  0.060323   

         21        22        23        24        25        26        27  
0  0.027974  0.038102  0.037961  0.051714  0.049363  0.054282  0.067418  
1  0.043068  0.058873  0.057672  0.096760  0.063362  0.081685  0.089802  
2  0.037498  0.058830  0.064907  0.091701  0.074951  0.059872  0.061053  
3  0.074634  0.070410  0.081935  0.117705  0.146539  0.129029  0.124808  
4  0.062509  0.090917  0.098685  0.117453  0.122942  0.101433  0.137708  

[5 rows x 29 columns]

# Merger the same files name

In [45]:
merged = pd.merge(TrainLabel,NewAll,left_on='File',right_on='FileName')
M=merged

In [46]:
merged.head()

Category Event     File FileName         0         1         2         3  \
0  Effects  Beep  TN7.wav  TN7.wav  0.673079  0.098229  0.375247  0.791839   
1  Effects  Beep  RTS.wav  RTS.wav  0.614813  0.295177  0.373146  0.761832   
2  Effects  Beep  NUO.wav  NUO.wav  0.641462  0.311208  0.285988  0.604421   
3  Effects  Beep  CPU.wav  CPU.wav  0.500055  0.063915  0.247723  0.680380   
4  Effects  Beep  SB2.wav  SB2.wav  0.982776  0.576084  0.123782  0.528756   

          4         5    ...           18        19        20        21  \
0  0.404122  0.226550    ...     0.110271  0.348035  0.065274  0.058471   
1  0.472383  0.447588    ...     0.064446  0.039347  0.030562  0.052972   
2  0.341296  0.707173    ...     0.031808  0.011694  0.011562  0.012332   
3  0.604663  0.455493    ...     0.028421  0.029188  0.041799  0.135779   
4  0.735243  0.550403    ...     0.049353  0.014900  0.010943  0.010131   

         22        23        24        25        26        27  
0  0.075210  0.306330  0.172177  0.176376  0.305487  0.143139  
1  0.109096  0.068888  0.085426  0.102243  0.131408  0.626913  
2  0.013816  0.016165  0.023563  0.022902  0.015057  0.019551  
3  0.261494  0.097300  0.092645  0.229316  0.064318  0.056040  
4  0.010621  0.022637  0.454293  0.043626  0.036094  0.049567  

[5 rows x 32 columns]

In [47]:
# newwriter = pd.ExcelWriter('merged.xlsx')
# merged.to_excel(newwriter,'Sheet1')
# newwriter.save()

# Categorical name to discrete number

In [48]:
M['labelumn'] = pd.factorize(M['Category'], sort=True)[0] + 1
M.head()

Category Event     File FileName         0         1         2         3  \
0  Effects  Beep  TN7.wav  TN7.wav  0.673079  0.098229  0.375247  0.791839   
1  Effects  Beep  RTS.wav  RTS.wav  0.614813  0.295177  0.373146  0.761832   
2  Effects  Beep  NUO.wav  NUO.wav  0.641462  0.311208  0.285988  0.604421   
3  Effects  Beep  CPU.wav  CPU.wav  0.500055  0.063915  0.247723  0.680380   
4  Effects  Beep  SB2.wav  SB2.wav  0.982776  0.576084  0.123782  0.528756   

          4         5    ...           19        20        21        22  \
0  0.404122  0.226550    ...     0.348035  0.065274  0.058471  0.075210   
1  0.472383  0.447588    ...     0.039347  0.030562  0.052972  0.109096   
2  0.341296  0.707173    ...     0.011694  0.011562  0.012332  0.013816   
3  0.604663  0.455493    ...     0.029188  0.041799  0.135779  0.261494   
4  0.735243  0.550403    ...     0.014900  0.010943  0.010131  0.010621   

         23        24        25        26        27  labelumn  
0  0.306330  0.172177  0.176376  0.305487  0.143139         1  
1  0.068888  0.085426  0.102243  0.131408  0.626913         1  
2  0.016165  0.023563  0.022902  0.015057  0.019551         1  
3  0.097300  0.092645  0.229316  0.064318  0.056040         1  
4  0.022637  0.454293  0.043626  0.036094  0.049567         1  

[5 rows x 33 columns]

# Separate Features and class labels

In [49]:
Features=merged.iloc[:,4:32]
labels=merged.iloc[:,0]
#labels.head()

In [50]:
X_train, X_test, y_train, y_test = train_test_split(Features,labels, test_size=.20, random_state=40) 
np.unique(y_test,return_counts=True)

(array(['Effects', 'Human', 'Music', 'Nature', 'Urban'], dtype=object),
 array([62, 57, 56, 77, 48], dtype=int64))

In [51]:
type(y_test)

pandas.core.series.Series

In [52]:
y_test.head()

1044    Nature
1150    Nature
771      Music
1171    Nature
621      Music
Name: Category, dtype: object

In [53]:
# cv=5
# from sklearn.model_selection import GridSearchCV
# parameters = {'kernel':('linear', 'rbf','poly'), 'C':[1, 10,100],'gamma':[0.01,.002]}
# svc = svm.SVC()
# clf = GridSearchCV(svc, parameters,cv=cv)
# clf.fit(X_train, y_train)

In [54]:
# from sklearn.tree import DecisionTreeClassifier
# dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train)
# dtree_predictions = dtree_model.predict(X_test)
# #accuracy=dtree_predictions.score(X_test, y_test)

# Training a DescisionTreeClassifier [link](https://www.geeksforgeeks.org/multiclass-classification-using-scikit-learn/)

# Decision tree

In [55]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=42)
dtree_model=clf.fit(X_train,y_train)
dtree_predictions=dtree_model.predict(X_test)
#cross_val_score(clf, Features, labels, cv=10)
score=cross_val_score(clf, X_train, y_train, cv=5)
# Mean score
score.mean()

0.00082644628099173552

# Confusion matrix and accuracy of DT

In [56]:
# cm = confusion_matrix(y_test, dtree_predictions)
# cm

In [57]:
# acctre=accuracy_score(y_test, dtree_predictions)
# print("The accucracy of DT is %2f:" % acctre)

# SVM classifier

In [58]:
clf = svm.SVC(kernel='linear', C=5)
scores = cross_val_score(clf, X_train, y_train, cv=5)
scores

array([ 0.15289256,  0.1446281 ,  0.12033195,  0.18067227,  0.14345992])

# Average accuracy

In [59]:
print("Accuracy:%0.3f (+/-%0.3f)" %(scores.mean(), scores.std()*2))

Accuracy:0.148 (+/-0.039)


# ShuffleSplit (Other Cross-validation)

In [60]:
from sklearn.model_selection import ShuffleSplit
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
cr=cross_val_score(clf, Features, labels, cv=cv)
cr

array([ 0.15111111,  0.11555556,  0.12666667,  0.12888889,  0.12      ])

# Average Accuracy for shuffle split

In [61]:
print("Accuracy:%0.3f (+/-%0.3f)" %(cr.mean(), cr.std()*2))

Accuracy:0.128 (+/-0.025)


# Gridserach CV

In [62]:
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
parameters = {'kernel':('linear', 'rbf','poly','sigmoid'), 'C':[1, 10,100],'gamma':[0.01,.002]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters,cv=cv)
clf.fit(Features, labels)

GridSearchCV(cv=ShuffleSplit(n_splits=5, random_state=0, test_size=0.3, train_size=None),
       error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'kernel': ('linear', 'rbf', 'poly', 'sigmoid'), 'C': [1, 10, 100], 'gamma': [0.01, 0.002]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

# Find the score

In [63]:
clf.cv_results_['mean_test_score']

array([ 0.13733333,  0.17822222,  0.17911111,  0.17822222,  0.13733333,
        0.17822222,  0.17911111,  0.17822222,  0.12311111,  0.16933333,
        0.17911111,  0.176     ,  0.12311111,  0.17822222,  0.17911111,
        0.17822222,  0.12177778,  0.13244444,  0.17911111,  0.13688889,
        0.12177778,  0.15777778,  0.17911111,  0.16888889])

# Find the best parameters

In [64]:
clf.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.01, kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [65]:
acc=accuracy_score(clf.best_estimator_.predict(X_test),y_test)
print acc

0.186666666667


In [66]:
#sorted(clf.cv_results_.keys())

In [67]:
#clf.cv_results_

# Confusion Matrix

In [68]:
# pred=clf.best_estimator_.predict(X_test)
# conf_mat=confusion_matrix(y_test,pred)
# #conf_mat
# # conf_mat=confusion_matrix(y_test,pred)
# conf_mat

In [69]:
pred=clf.best_estimator_.predict(X_test)
pd.DataFrame(
    confusion_matrix(y_test, pred),
    columns=['Predict Effects', 'Predict Human', 'Predict Music', 'Predict Nature', 'Predict Urban'],
    index=[' True Effects', 'True Human', ' True Music', ' True Nature', 'True Urban'])

Predict Effects  Predict Human  Predict Music  Predict Nature  \
 True Effects               15             13             13               4   
True Human                  18             16              8               2   
 True Music                 18             13              7               6   
 True Nature                22             17             11              11   
True Urban                  19              9              9               4   

               Predict Urban  
 True Effects             17  
True Human                13  
 True Music               12  
 True Nature              16  
True Urban                 7

In [70]:
df=pd.DataFrame(pred)
np.unique(df,return_counts=True)

(array(['Effects', 'Human', 'Music', 'Nature', 'Urban'], dtype=object),
 array([92, 68, 48, 27, 65], dtype=int64))

In [71]:
np.unique(y_test,return_counts=True)

(array(['Effects', 'Human', 'Music', 'Nature', 'Urban'], dtype=object),
 array([62, 57, 56, 77, 48], dtype=int64))

In [72]:
# cmap=plt.cm.RdBu
# plt.imshow(cm, interpolation='nearest', cmap=cmap)

# Gaussian Naive Bayes

In [73]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [74]:
y_pred=gnb.fit(X_train,y_train).predict(X_test)
#y_pred.results

In [75]:
print("Number of mislabeled points out of a total %d points : %d"
      % (y_test.shape[0],(y_test != y_pred).sum()))

Number of mislabeled points out of a total 300 points : 233


In [76]:
acc=(1-(y_test!= y_pred).sum()/300.0)*100
print("Accuracy %f" %acc)

Accuracy 22.333333


In [77]:
conf_mat=confusion_matrix(y_test,y_pred)
conf_mat

array([[ 5,  1,  2, 52,  2],
       [11,  0,  0, 43,  3],
       [10,  1,  0, 43,  2],
       [ 9,  1,  4, 60,  3],
       [ 7,  1,  4, 34,  2]])

In [78]:
# (y_test!=y_pred).sum())

# Random Forest [link](https://www.codementor.io/agarrahul01/multiclass-classification-using-random-forest-on-scikit-learn-library-hkk4lwawu)

In [79]:
X_train.head()

0         1         2         3         4         5         6  \
1000  0.565927  0.062321  0.605505  0.757441  0.416050  0.137693  0.301277   
758   0.496948  0.060784  0.988192  0.626046  0.330987  0.530650  0.529727   
275   0.449015  0.024891  0.863819  0.594888  0.172614  0.554936  0.624290   
1374  0.710695  0.703165  0.337943  0.710753  0.347792  0.282751  0.693989   
169   0.743094  0.538332  0.757791  0.715021  0.355054  0.419846  0.506123   

             7         8         9    ...           18        19        20  \
1000  0.492763  0.183344  0.494988    ...     0.099967  0.060979  0.057405   
758   0.587944  0.406455  0.620249    ...     0.031683  0.008360  0.010567   
275   0.657680  0.219736  0.687320    ...     0.029948  0.008970  0.023883   
1374  0.604293  0.289740  0.718021    ...     0.112670  0.046146  0.244591   
169   0.649879  0.478414  0.557658    ...     0.105570  0.037983  0.032973   

            21        22        23        24        25        26        27  
1000  0.113699  0.108173  0.120115  0.161687  0.175636  0.185065  0.170363  
758   0.012873  0.021534  0.025392  0.045471  0.053987  0.033033  0.036488  
275   0.020302  0.027263  0.077836  0.036178  0.105470  0.063213  0.028900  
1374  0.064841  0.317705  0.106215  0.270558  0.095962  0.166072  0.157131  
169   0.036718  0.041276  0.048738  0.067786  0.066048  0.088411  0.108770  

[5 rows x 28 columns]

# pd to numpy

In [80]:
#Creating the dependent variable class
factor = pd.factorize(M['Category'])
M.Category = factor[0]
definitions = factor[1]
print(M.Category.head())
print(definitions)

0    0
1    0
2    0
3    0
4    0
Name: Category, dtype: int64
Index([u'Effects', u'Human', u'Music', u'Nature', u'Urban'], dtype='object')


In [81]:
# Fitting Random Forest Classification to the Training set
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=42,
            verbose=0, warm_start=False)

In [82]:
y_pred = classifier.predict(X_test)
y1=y_test
#print y1

In [83]:
print(pd.crosstab(y_test, y_pred, rownames=['Actual Species'], colnames=['Predicted Species']))

Predicted Species  Effects  Human  Music  Nature  Urban
Actual Species                                         
Effects                  0     18     15      16     13
Human                   15      0     14      15     13
Music                   19     11      0      14     12
Nature                  24     24     18       0     11
Urban                    7     11     18      12      0


In [84]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(pd.crosstab(y_test, y_pred, rownames=['Actual Species'], colnames=['Predicted Species']))

Predicted Species  Effects  Human  Music  Nature  Urban
Actual Species                                         
Effects                  0     18     15      16     13
Human                   15      0     14      15     13
Music                   19     11      0      14     12
Nature                  24     24     18       0     11
Urban                    7     11     18      12      0


In [85]:
classifier.feature_importances_

array([ 0.03782975,  0.0360923 ,  0.03902163,  0.0292145 ,  0.03483865,
        0.03466608,  0.04199399,  0.0377297 ,  0.04498029,  0.04226971,
        0.03805325,  0.04060423,  0.0498758 ,  0.04232317,  0.03425594,
        0.03803361,  0.03004865,  0.03039045,  0.03211259,  0.02948754,
        0.02908873,  0.03544394,  0.03318292,  0.03079016,  0.03367091,
        0.02793858,  0.03320433,  0.03285861])

In [86]:
# # Predicting the Test set results
# y_pred = classifier.predict(X_test)
# #Reverse factorize (converting y_pred from 0s,1s and 2s to Iris-setosa, Iris-versicolor and Iris-virginica
# reversefactor = dict(zip(range(5),definitions))
# y_test = np.vectorize(reversefactor.get)(y_test)
# y_pred = np.vectorize(reversefactor.get)(y_pred)
# # Making the Confusion Matrix
# print(pd.crosstab(y_test, y_pred, rownames=['Actual Species'], colnames=['Predicted Species']))